### ISSUE TITLE
language=NL

### ISSUE THREAD

**Issue by TessaViergever** [Patrickkhr/your-tribe-squad-page#1]
https://github.com/Patrickkhr/your-tribe-squad-page/blob/a803df850bfd73fc18657f905dccd0e80348a430/index.html#L2C27-L2C27

Je gebruikt Nederlands in je document dus deze mag op NL ipv EN (:

**Comment by Patrickkhr** [comment]
Bedankt voor de feedback. We hebben het aangepast en opgelost: https://github.com/Patrickkhr/your-tribe-squad-page/blob/dbfa2764c4b1cb0c9a3b7de8af637904d28cf588/index.html#L2C17-L2C17
