### ISSUE TITLE
Tip voor het documenteren van de Dev-lifecycle!

### ISSUE THREAD

**Issue by Siem-P** [Patrickkhr/your-tribe-squad-page#4]
<img width="1105" alt="Screenshot 2023-09-20 at 10 31 03" src="https://github.com/Patrickkhr/your-tribe-squad-page/assets/64197688/5f5337bc-1342-47be-b7f6-d4568cae44fd">

**Comment by Patrickkhr** [comment]
Bedankt voor de tip!
